# Generated by Django 4.2.5 on 2023-10-01 13:22

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='video record')),
                ('video', models.FileField(blank=True, null=True, upload_to=core.models.video_dir, verbose_name='video file')),
                ('caption', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='VideoByteChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_number', models.PositiveSmallIntegerField(verbose_name='chunk number')),
                ('chunk_file', models.FileField(upload_to=core.models.chunk_dir, verbose_name='video chunk')),
                ('is_last', models.BooleanField(default=False, verbose_name='last chunk')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.videorecord')),
            ],
            options={
                'ordering': ['chunk_number'],
            },
        ),
    ]
